---
title: "Game Clustering Model"
author: "Govin Nagpal"
date: "4/27/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r}
#Read in the data
library(readxl)
game_clustering_jets <- read_excel("~/Downloads/Game_Clustering_Jets (2).xlsx")
game_clustering_jets

#Bin the average price column
# binavg <- quantile(game_clustering_jets$Average_Price, probs = seq(0,1,length.out=4))
# game_clustering_jets$bin_average <- cut(game_clustering_jets$Average_Price, breaks = binavg, include.lowest=T, right=F)
# 
# #Bin the median price column
# binmed <- quantile(game_clustering_jets$Median_Price, probs = seq(0,1,length.out=4))
# game_clustering_jets$bin_median <- cut(game_clustering_jets$Median_Price, breaks = binmed, include.lowest=T, right=F)
# 
# #Check out the new columns
# game_clustering_jets
# 
# #Write the csv
# write.csv(game_clustering_jets, "game_clustering_jets_bins.csv")


#Create the model
# model1 <- glm(Average_Price~GameType+ELO+Facebook_Followers*Percentage_W_previous_season,data=game_clustering_jets)
# summary(model1)


#New variables Gavin created
game_clustering_jets$TOD <- ifelse(game_clustering_jets$'Time of the day' == "Noon", 1,
                               ifelse(game_clustering_jets$'Time of the day' == "Afternoon", 2, 3))


#Transform GameType variable to GT
game_clustering_jets$GT <- ifelse(game_clustering_jets$GameType == "Preseason", 2, 1)


#Transform Event_Day variable to DOW
game_clustering_jets$DOW <- ifelse(game_clustering_jets$Event_Day == "Thursday", 1,
                               ifelse(game_clustering_jets$Event_Day== "Friday", 2,
                                      ifelse(game_clustering_jets$Event_Day== "Saturday", 3, 
                                             ifelse(game_clustering_jets$Event_Day== "Sunday", 4, 5))))


#Transform Month variable to Weather
game_clustering_jets$Weather <- ifelse(game_clustering_jets$Month == "August", 1,
                               ifelse(game_clustering_jets$Month== "September", 2,
                                      ifelse(game_clustering_jets$Month== "October", 3, 
                                             ifelse(game_clustering_jets$Month== "November", 4,
                                                    ifelse(game_clustering_jets$Month== "December", 5, 5)))))


```


```{r, Raw data and adding in new variables}
#Read the Ticket Exchange data in 
setwd("~/Documents")
library(readxl)
Ticket_Exchange_raw <- read.csv("~/Documents/Ticket Exchange.csv")
Ticket_Exchange_raw


#Create a new variable called Time_Before that find the difference between the event day and the day the ticket was purchases
Ticket_Exchange_raw$Time_Before <- difftime(Ticket_Exchange_raw$event_date, Ticket_Exchange_raw$add_datetime, units= "days")


#Convert negative values in Time_before to 0.
Ticket_Exchange_raw$Time_Before <- ifelse(Ticket_Exchange_raw$Time_Before <0, 0, Ticket_Exchange_raw$Time_Before)


#Create buckets for different purchase times
Ticket_Exchange_raw$purchase_date <- ifelse(Ticket_Exchange_raw$Time_Before == 0, "Day_of", ifelse(Ticket_Exchange_raw$Time_Before<=7 & Ticket_Exchange_raw$Time_Before>0, "Week_of", ifelse(Ticket_Exchange_raw$Time_Before<=28 & Ticket_Exchange_raw$Time_Before>7, "4_Weeks", "months_before")))
Ticket_Exchange_raw$purchase_day_of <- ifelse(Ticket_Exchange_raw$purchase_date == "Day_of", 1, 0)
Ticket_Exchange_raw$purchase_week_of <- ifelse(Ticket_Exchange_raw$purchase_date == "Week_of", 1, 0)
Ticket_Exchange_raw$purchase_month_of <- ifelse(Ticket_Exchange_raw$purchase_date == "4_Weeks", 1, 0)
Ticket_Exchange_raw$purchase_over_month_out <- ifelse(Ticket_Exchange_raw$purchase_date == "months_before", 1, 0)
```



```{r, Remove missing data and transform data }
#Remove the missing data from the Ticket Exchange file
Ticket_Exchange <- Ticket_Exchange_raw[!Ticket_Exchange_raw$te_posting_price == "NULL", ] 
Ticket_Exchange <- na.omit(Ticket_Exchange)

#Change the variable type of posting price from character to numeric 
Ticket_Exchange$te_posting_price <- as.numeric(Ticket_Exchange$te_posting_price)


#Read the Price Level Section Mapping data in
Price_Level_Section_Mapping_raw <- read.csv("~/Downloads/Price Level Section Mapping.csv")

#Merge price level section mapping dataset and ticket exchange data set on section, row, and seat
library(tidyverse)
Ticket_Exchange <- Ticket_Exchange %>% 
  rename(
    Section = section_name,
    Row = row_name,
    Seat = seat_num
    )

#Merge the Ticket_Exchange and the Price_Level_Section_Mapping data sets
tickets <- merge(Price_Level_Section_Mapping_raw, Ticket_Exchange, by = c("Section", "Row", "Seat"))

#Rename the ID variable to event_id
game_clustering_jets <- game_clustering_jets %>% 
  rename(
    event_id = ID
    )

#Remove NULL values from the te_purchase_price column
tickets <- tickets %>%
  filter(te_purchase_price!="NULL")

#Merge the already merged ticket data from above with the Excel spreadsheet data we created 
tickets_all <- merge(tickets, game_clustering_jets,  by="event_id")

#Change the type of Rows from character to integer
tickets_all$Row <- as.numeric(tickets_all$Row)

unique(tickets_all$activity_name)

#Filter by stadium level
lower_level <- tickets_all %>% 
  filter(Level == "Lower")
club_level <- tickets_all %>% 
  filter(Level == "Club")
mezzanine_level <- tickets_all %>% 
  filter(Level == "Mezzanine")
upper_level <- tickets_all %>% 
  filter(Level == "Upper")


#Regression

lower_levelno2019 <- lower_level %>%
  filter(season_year!=2019)

lower_level2019 <- lower_level %>%
  filter(season_year==2019)

# model1 <- lm(te_purchase_price~season_year+Opponent+Event_Day+Month+Facebook_Followers+Percentage_W_previous_season+Section, data=lower_levelno2019)
# summary(model1)
# predict(model1, data.frame(season_year=2019, Opponent="New Orleans Saints", Event_Day="Saturday", Month="August", Facebook_Followers=4020000, Percentage_W_previous_season=0.813, Section="126"))

#Remove leading whitespace in Opponent names
lower_level2019$Opponent <- str_trim(lower_level2019$Opponent , side ="right")
model1 <- lm(te_purchase_price~season_year+Opponent+Event_Day+Month+Facebook_Followers+Percentage_W_previous_season+Section+Row+Seat+ELO, data=lower_levelno2019)
summary(model1)


#Create a new data set with only the important variables
subset_dataset_for_prediction <- lower_level2019 %>%
  select(season_year, Opponent, Event_Day, Month, Facebook_Followers, Percentage_W_previous_season, Section,Row, Seat, ELO)

#Predict the purchase price based on our model
lower_level<- predict(model1, newdata = subset_dataset_for_prediction)


lower_model1 <- lm(te_purchase_price ~ purchase_week_of + purchase_month_of + purchase_over_month_out, data=lower_level)
summary(lower_model1)

club_model1 <- lm(te_purchase_price ~ purchase_week_of + purchase_month_of + purchase_over_month_out, data=club_level)
summary(club_model1)

mezzanine_model1 <- lm(te_purchase_price ~ purchase_week_of + purchase_month_of + purchase_over_month_out, data=mezzanine_level)
summary(mezzanine_model1)

upper_model1 <- lm(te_purchase_price ~ purchase_week_of + purchase_month_of + purchase_over_month_out, data=upper_level)
summary(upper_model1)

Ticket_Exchange_raw %>% 
  arrange(purchase_week_of, desc=T)
```

