---
title: "K-Means Clustering Model"
author: "Govin Nagpal"
date: "4/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r}
# Game clustering 

#Import the packages
library(readxl)
library(stats)

#Read in the excel file
Game_Clustering_Jets <- read_excel("~/Downloads/Game_Clustering_Jets (3).xlsx", sheet="Sheet1")

#Create linear regression model
model <- lm(Median_Price ~ GameType + Percentage_W_previous_season, 
            data = Game_Clustering_Jets)
summary(model)


#Only 3 numerical variables 
Clustering <- Game_Clustering_Jets[c("ELO", "Facebook_Followers", "Percentage_W_previous_season")]
Clustering

#Kmeans clustering on 3 numerical variables
x <- kmeans(Clustering, centers = 3, iter.max = 10, nstart = 1)
x$cluster


Game_Clustering_Jets$cluster <- ifelse(x$cluster==1,1,ifelse(x$cluster==2,2,3))
Game_Clustering_Jets$cluster <- as.factor(Game_Clustering_Jets$cluster)


Game_Clustering_Jets %>% 
  group_by(cluster) %>% 
  summarise(mean = mean(Median_Price))


#install.packages("factoextra")
#install.packages("broom")
# library(factoextra)
# 
# elbow <- fviz_nbclust(Clustering, FUNcluster = kmeans, method="wss")
# elbow
```


```{r}
#Transform Time of Day variable to TOD
Game_Clustering_Jets$TOD <- ifelse(Game_Clustering_Jets$'Time of the day' == "Noon", 1,
                               ifelse(Game_Clustering_Jets$'Time of the day' == "Afternoon", 2, 3))


#Transform GameType variable to GT
Game_Clustering_Jets$GT <- ifelse(Game_Clustering_Jets$GameType == "Preseason", 2, 1)


#Transform Event_Day variable to DOW
Game_Clustering_Jets$DOW <- ifelse(Game_Clustering_Jets$Event_Day == "Thursday", 1,
                               ifelse(Game_Clustering_Jets$Event_Day== "Friday", 2,
                                      ifelse(Game_Clustering_Jets$Event_Day== "Saturday", 3, 
                                             ifelse(Game_Clustering_Jets$Event_Day== "Sunday", 4, 5))))


#Transform Month variable to Weather
Game_Clustering_Jets$Weather <- ifelse(Game_Clustering_Jets$Month == "August", 1,
                               ifelse(Game_Clustering_Jets$Month== "September", 2,
                                      ifelse(Game_Clustering_Jets$Month== "October", 3, 
                                             ifelse(Game_Clustering_Jets$Month== "November", 4,
                                                    ifelse(Game_Clustering_Jets$Month== "December", 5, 5)))))




#Select the new variables 
Clustering <- Game_Clustering_Jets[,c("ELO", "Facebook_Followers", "Percentage_W_previous_season", "TOD", "GT", "DOW", "Weather")]
Clustering

#Run kmeans clustering 
x <- kmeans(Clustering, centers = 3, iter.max = 10, nstart = 1)

x$cluster
Game_Clustering_Jets$cluster <- ifelse(x$cluster==1,1,ifelse(x$cluster==2,2,3))
Game_Clustering_Jets$cluster <- as.factor(Game_Clustering_Jets$cluster)
Game_Clustering_Jets %>% group_by(cluster) %>% 
  summarise(mean = mean(Median_Price))


Clustering_on_price <- Game_Clustering_Jets[c("Median_Price")]
Clustering_on_price
y <- kmeans(Clustering_on_price, centers = 3, iter.max = 10, nstart = 1)
y$cluster
Game_Clustering_Jets$cluster_test <- ifelse(y$cluster==1,1,ifelse(y$cluster==2,2,3))
Game_Clustering_Jets$cluster_test <- as.factor(Game_Clustering_Jets$cluster_test)
Game_Clustering_Jets %>% group_by(cluster_test) %>% 
  summarise(mean = mean(Median_Price))

```

```{r}
#Scale the data in the Clustering Data 

#Run PCA analysis
pca <- prcomp(Clustering, scale. = T)
data.frame(pca$x)
?prcomp

#Plot the principal components
biplot(pca, scale=0)

#DETERMINE THE NUMBER OF PRINCIPAL COMPONENTS WE SHOULD USE 
pca_std <- pca$sdev
pca_var <- pca_std^2
pca_prop_var <- pca_var/sum(pca_var)
pca_prop_var
#Check using a scree plot and cumulative scree plot how many principal components we should use
plot(pca_prop_var, xlab= "Principal Component", 
     ylab="Proportion of Variance Explained", 
     type="b")
plot(cumsum(pca_prop_var), xlab = "Principal Component", 
     ylab = "Cumulative Proportion of Variance Explained", 
     type = "b")
#WE SHOULD USE ALL 7

```

